# Generated by Django 3.2.7 on 2022-01-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='investmentstate',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
