# Generated by Django 3.2.7 on 2022-01-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20220113_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
