# Generated by Django 3.2.7 on 2022-01-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_alter_investment_maitrise_d_oeuvre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='notification_du_marche',
            field=models.DateField(null=True),
        ),
    ]
